version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: card_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ismoil_0709
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "8081:8081"

  app:
    build: .
    container_name: card-processing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/card_processing
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ismoil_0709
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres-data:
