spring:
  security:
    oauth2:
      client:
        registration:
          google.client-id:      442992578451-os7ft8tbttn7krssi8dufrunqc2ndnud.apps.googleusercontent.com
          google.client-secret:  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
  mail:
    host: smtp.gmail.com
    port: 587
    username: abduganiyev.ismoil001@gmail.com
    password: lkeu ioml dypp zwed
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  application:
    name: fast-food-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123321
    url: jdbc:postgresql://localhost:5432/fast_food_app
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cache:
    redis:
      time-to-live: 1d
jwt:
  token:
    secret:
      expiry: 604800000 # 1 month
      key: VGhpcyBpcyBrZXkgZm9yIEpXVApNeSBuYW1lIGlzIElzbW9pbApNeSBiaXJ0aCBkYXkgMDcuMDkuMjAwNw==